name: "GitOps CI"

on:
  push:
    branches:
    - 'master'    
    paths:
    - 'cluster.yaml'

jobs:
  gitops:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out cluster template ...
      uses: actions/checkout@v1
    - name: Provisioning GitOps-based cluster ...
      uses: chanwit/action-eksctl@v13
      with:
        awsAccessKeyId: ${{ secrets.awsAccessKeyId }}
        awsSecretAccessKey: ${{ secrets.awsSecretAccessKey }}
        githubToken: ${{ secrets.githubToken }}
