name: "GitOps CI"

on:
  push:
    paths:
    - 'cluster.yaml'

jobs:
  gitops:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: chanwit/action-eksctl@v1
      with:
        region: us-west-2
        awsAccessKeyId: ${{ secrets.awsAccessKeyId }}
        awsSecretAccessKey: ${{ secrets.awsSecretAccessKey }}
